[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/atom.xml"
to = "/feed.xml"
status = 301

[[redirects]]
from = "/posts/:id/index.html"
to = "/post/:id"
status = 301

[[redirects]]
from = "/posts/:id"
to = "/post/:id"
status = 301

[[redirects]]
from = "/favicon.png"
to = "/assets/images/favicon.png"
status = 301

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
