minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@twikoojs/shared'
  - twikoo
  - vite

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar

shellEmulator: true
verifyDepsBeforeRun: false

patchedDependencies:
  vite-ssg: patches/vite-ssg.patch

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
