import { mkdir, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { normalizeStringList } from '../src/content/post-policy'
import { parsePostFiles } from './parse-post-files'
import { extractPostImage } from './seo/extract-post-image'

export async function generatePostsMeta(outFile = '.auto-generate/posts-meta.ts'): Promise<void> {
  const posts = await parsePostFiles()

  // parsePostFiles 已按日期降序排列
  const records = posts.map(({ path, data, content, date }) => ({
    path,
    title: String(data.title ?? ''),
    date,
    tags: normalizeStringList(data.tags),
    categories: normalizeStringList(data.categories),
    image: extractPostImage(data, content) ?? undefined
  }))

  const source = `/* eslint-disable */
// This file is auto-generated by scripts/generate-posts-meta.ts
import type { PostListEntry } from '../src/content/post-policy'

export const postsMeta: PostListEntry[] = ${JSON.stringify(records, null, 2)}

export default postsMeta
`

  await mkdir(dirname(outFile), { recursive: true })
  await writeFile(outFile, source, 'utf-8')
}
