import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import matter from 'gray-matter'
import { glob } from 'tinyglobby'
import { postPublicPath } from '../src/constants/route-policy'
import {
  formatPostDateString,
  isPublishablePostData,
  normalizeNumericPostId,
  normalizeStringList,
  sortPostListEntriesByDateDesc
} from '../src/content/post-policy'
import { POSTS_CONTENT_GLOB, POSTS_ROOT_INDEX_FILE } from './post-content-paths'
import { extractPostImage } from './seo/extract-post-image'

interface GeneratedPostMeta {
  path: string
  title: string
  date: string
  tags: string[]
  categories: string[]
  image?: string
}

export async function generatePostsMeta(outFile = '.auto-generate/posts-meta.ts'): Promise<void> {
  const files = await glob(POSTS_CONTENT_GLOB)
  const records: GeneratedPostMeta[] = []

  for (const file of files) {
    if (file === POSTS_ROOT_INDEX_FILE)
      continue

    const raw = await readFile(file, 'utf-8')
    const { data, content } = matter(raw)

    if (!isPublishablePostData(data))
      continue

    const idStr = normalizeNumericPostId(data as Record<string, unknown>)
    if (!idStr)
      continue

    records.push({
      path: postPublicPath(idStr),
      title: String(data.title ?? ''),
      date: formatPostDateString(data.date),
      tags: normalizeStringList(data.tags),
      categories: normalizeStringList(data.categories),
      image: extractPostImage(data as Record<string, unknown>, content) ?? undefined
    })
  }

  const sortedRecords = sortPostListEntriesByDateDesc(records)
  const source = `/* eslint-disable */
// This file is auto-generated by scripts/generate-posts-meta.ts
import type { PostListEntry } from '../src/content/post-policy'

export const postsMeta: PostListEntry[] = ${JSON.stringify(sortedRecords, null, 2)}

export default postsMeta
`

  await mkdir(dirname(outFile), { recursive: true })
  await writeFile(outFile, source, 'utf-8')
}
